# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from test_proto1.proto import test_pb2 as test__proto1_dot_proto_dot_test__pb2


class YourTestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.unary_unary(
        '/YourTest/hello',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.User.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.FromString,
        )


class YourTestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.unary_unary_rpc_method_handler(
          servicer.hello,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.User.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YourTest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class YourTest1Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello1 = channel.unary_unary(
        '/YourTest1/hello1',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.User.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.FromString,
        )


class YourTest1Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTest1Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello1': grpc.unary_unary_rpc_method_handler(
          servicer.hello1,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.User.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YourTest1', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
