# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto1/proto/test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_proto1/proto/test.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1ctest_proto1/proto/test.proto\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x18\n\x08UserInfo\x12\x0c\n\x04info\x18\x01 \x01(\t2)\n\x08YourTest\x12\x1d\n\x05hello\x12\x05.User\x1a\t.UserInfo\"\x00(\x01\x32*\n\tYourTest1\x12\x1d\n\x05hello\x12\x05.User\x1a\t.UserInfo\"\x00\x30\x01\x32,\n\tYourTest2\x12\x1f\n\x05hello\x12\x05.User\x1a\t.UserInfo\"\x00(\x01\x30\x01\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=64,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='UserInfo.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'test_proto1.proto.test_pb2'
  # @@protoc_insertion_point(class_scope:User)
  ))
_sym_db.RegisterMessage(User)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERINFO,
  __module__ = 'test_proto1.proto.test_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)



_YOURTEST = _descriptor.ServiceDescriptor(
  name='YourTest',
  full_name='YourTest',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=133,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='YourTest.hello',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USERINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOURTEST)

DESCRIPTOR.services_by_name['YourTest'] = _YOURTEST


_YOURTEST1 = _descriptor.ServiceDescriptor(
  name='YourTest1',
  full_name='YourTest1',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=135,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='YourTest1.hello',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USERINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOURTEST1)

DESCRIPTOR.services_by_name['YourTest1'] = _YOURTEST1


_YOURTEST2 = _descriptor.ServiceDescriptor(
  name='YourTest2',
  full_name='YourTest2',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=179,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='YourTest2.hello',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USERINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOURTEST2)

DESCRIPTOR.services_by_name['YourTest2'] = _YOURTEST2

# @@protoc_insertion_point(module_scope)
