# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from test_proto1.proto import test_pb2 as test__proto1_dot_proto_dot_test__pb2


class YourTestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.stream_unary(
        '/test1.YourTest/hello',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.User.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.FromString,
        )


class YourTestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.stream_unary_rpc_method_handler(
          servicer.hello,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.User.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test1.YourTest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class YourTest1Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.unary_stream(
        '/test1.YourTest1/hello',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.User.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.FromString,
        )


class YourTest1Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTest1Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.unary_stream_rpc_method_handler(
          servicer.hello,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.User.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test1.YourTest1', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class YourTest2Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.stream_stream(
        '/test1.YourTest2/hello',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.User.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.FromString,
        )


class YourTest2Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTest2Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.stream_stream_rpc_method_handler(
          servicer.hello,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.User.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test1.YourTest2', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class YourTest3Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.unary_unary(
        '/test1.YourTest3/hello',
        request_serializer=test__proto1_dot_proto_dot_test__pb2.AllUser.SerializeToString,
        response_deserializer=test__proto1_dot_proto_dot_test__pb2.AllUserInfo.FromString,
        )


class YourTest3Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YourTest3Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.unary_unary_rpc_method_handler(
          servicer.hello,
          request_deserializer=test__proto1_dot_proto_dot_test__pb2.AllUser.FromString,
          response_serializer=test__proto1_dot_proto_dot_test__pb2.AllUserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test1.YourTest3', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
